# Generated by Django 5.1.3 on 2024-12-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_defesa_delete_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defesa',
            options={'verbose_name': 'Defesa', 'verbose_name_plural': 'Defesas'},
        ),
        migrations.RemoveField(
            model_name='defesa',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='defesa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='defesa',
            name='ano_veiculo',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='defesa',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defesa',
            name='local_infracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defesa',
            name='modelo_veiculo',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='defesa',
            name='nome_motorista',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='defesa',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defesa',
            name='numero_infracao',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='defesa',
            name='placa_veiculo',
            field=models.CharField(default='Desconhecido', max_length=20),
        ),
        migrations.AlterField(
            model_name='defesa',
            name='descricao',
            field=models.TextField(default='Desconhecido'),
        ),
        migrations.AlterField(
            model_name='defesa',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Rejeitada', 'Rejeitada')], default='Em andamento', max_length=50),
        ),
    ]
